# Generated by Django 5.2.3 on 2025-12-07 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('total_likes', models.PositiveIntegerField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganadora_mes', to='mascotas.mascota')),
            ],
            options={
                'verbose_name': 'Ranking Mensual',
                'verbose_name_plural': 'Ranking Mensual',
                'ordering': ['-anio', '-mes'],
            },
        ),
    ]
